### PR TITLE
Update ResourceInputStream.php

### PR DESCRIPTION
**Pull request by bozhinov**
better code

### CODE REVIEW

**Comment by AydinHassan** [comment]
Why is it better?

**Comment by bozhinov** [comment]
less calls and get_resource_type would produce a warning.

**Comment by AydinHassan** [comment]
Why would it produce a warning? `get_resource_type` would never be called with a non resource?

**Comment by bozhinov** [comment]
true. I prefer my code anyway.
just pushing the changes I made to my internal repo
it is up for grabs but I won't mind if you don't

**Comment by AydinHassan** [comment]
Okay thanks but I prefer to keep it as it is :)

**Pull request closed without merging**
